### ISSUE TITLE
Support ghc 9.12

### ISSUE THREAD

**Issue by erikd** [phadej/boring#46]
Compiles with the following diff:
```
diff --git a/boring/boring.cabal b/boring/boring.cabal
index 564018f..6a38aec 100644
--- a/boring/boring.cabal
+++ b/boring/boring.cabal
@@ -47,7 +47,7 @@ flag tagged
 library
   exposed-modules:  Data.Boring
   build-depends:
-      base          >=4.12.0.0 && <4.21
+      base          >=4.12.0.0 && <4.22
     , transformers  >=0.5.6.2  && <0.7
 
   if impl(ghc <7.6)
```

**Comment by andreasabel** [comment]
> [__6] trying: shelly-1.12.1 (dependency of bnfc-system-tests)
> [__7] trying: lifted-async-0.10.2.7 (dependency of shelly)
> [__8] trying: constraints-0.14.2 (dependency of lifted-async)
> [__9] rejecting: boring-0.2.2 (conflict: process => base==4.21.0.0/installed-d274, boring => base>=4.12.0.0 && <4.21)
